#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh"
fi

export VISUAL=vim
export EDITOR="$VISUAL"

export PATH="$HOME/.yarn/bin:$PATH"

export NVM_DIR="/Users/rhio/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /Users/rhio/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /Users/rhio/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# theme
autoload -Uz promptinit
promptinit
prompt powerlevel9k
# prompt powerline
