#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh"
fi

export VISUAL=vim
export EDITOR="$VISUAL"

export GOROOT=/usr/local/go
export GOPATH=$HOME/Works/go
export PATH=$PATH:$HOME/Works/go/bin:$GOPATH/bin

export PATH="$HOME/.yarn/bin:$PATH"
export PATH=/Library/Frameworks/Python.framework/Versions/3.6/bin:$PATH

export NVM_DIR="/Users/rhio/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /Users/rhio/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /Users/rhio/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# theme
autoload -Uz promptinit
prompt powerlevel9k
# prompt powerline

# tabtab source for yarn package
# uninstall by removing these lines or running `tabtab uninstall yarn`
[[ -f /Users/rhio/.nvm/versions/node/v11.6.0/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh ]] && . /Users/rhio/.nvm/versions/node/v11.6.0/lib/node_modules/yarn-completions/node_modules/tabtab/.completions/yarn.zsh
source /Users/rhio/Library/Preferences/org.dystroy.broot/launcher/bash/br
