#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/aliases.zsh"
fi

export VISUAL=vim
export EDITOR="$VISUAL"

export PATH="$HOME/.yarn/bin:$PATH"
